### ISSUE TITLE
no-manual-cleanup does not like require(modulaName)

### ISSUE THREAD

**Issue by kentcdodds** [testing-library/eslint-plugin-testing-library#125]
I've got code like this:

```javascript
require(moduleName)
```

and no-manual-cleanup does this:

```
TypeError: Cannot read property 'match' of undefined
Occurred while linting /Users/kentcdodds/code/kcd-scripts/src/utils.js:39
    at VariableDeclarator (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint-plugin-testing-library/rules/no-manual-cleanup.js:71:73)
    at /Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
    at /Users/kentcdodds/code/kcd-scripts/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>)
```

This is because of this code:

https://github.com/testing-library/eslint-plugin-testing-library/blob/3439a29d9f9ae95b437be4c6cce72586ec4f094c/lib/rules/no-manual-cleanup.ts#L65-L66

It should check whether `value` exists before calling `match` :)

**Comment by Belco90** [comment]
Hey Kent! Thanks for open an issue so detailed. This one should be easy to fix, I'll try to take a look at it this weekend if no one else can address it before.

**Comment by Belco90** [comment]
@all-contibutors please add @kentcdodds for bugs

**Comment by Belco90** [comment]
@all-contributors please add @kentcdodds for bugs

**Comment by kentcdodds** [comment]
Sweet! Thanks 👍
